events/open-standup.md
This PR adds some advice for skipping tech lead updates on Mondays where we've done a sprint kickoff since we've already covered this stuff. I also did some random cleanup, hope that's ok! This closes https://github.com/artsy/potential/issues/170.
=> Skip tech lead updates on sprint kickoff Mondays

events/lunch-and-learn.md
I brought these over from the [old project board](https://github.com/artsy/meta/projects/1). I also added some internal ones to get a sense of what we talk about even when the speakers aren't external.
=> Adds some internal/external presentations to L&L docs

events/open-standup.md
This PR got lost in the docs migration, looks like: https://github.com/artsy/meta/pull/44. /cc @mbilokonsky
=> Applies artsy/meta#44

events/open-standup.md
This does a few things:
- Adds a note for moving laptops away from the Zoom speakerphone.
- Removes the announcement for writing office hours, since it robs me of an opportunity to really sell the event. It made sense to include in the template when I was running standup each week, but not anymore.
- Corrects the Show & Tell time.
=> Refreshes standup docs.

events/open-standup.md
This denotes:
* Team standup are optional
* That open RFCs are already published In the dev channel
* That if you're unsure about L&Ls then you can always asking the L&L channel
=> Adds comments to the inline walkthrough

culture/engineering-principles.md
Following [an RFC](https://github.com/artsy/potential/issues/177) discussed privately among Artsy engineers, we decided to add Psychological Safety to our list of engineering guiding principles. I added it second after "Open Source by Default" because OSS by Default is probably Artsy Engineering's defining characteristic, but Psychological Safety is critical as well (as evinced by the recent PDDE Culture ethnography, which is still a WIP).
@xtina-starr we've chatted a lot about this and I'd like to hear your feedback on the wording below. 
Fixes https://github.com/artsy/potential/issues/177.
=> Adds Psychological Safety to engineering guiding principles

.vscode/settings.json, culture/README.md, culture/highlights.md, culture/what-is-artsy.md
I'd like to do something similar to what I do [for Peril](https://github.com/danger/peril/issues/235) <a href="https://twitter.com/orta/status/1041421215431385089"><img src="https://user-images.githubusercontent.com/49038/39097791-55938788-4659-11e8-8f73-53c3480bfb15.png" height=12></a> , but for Artsy.
So if you have ideas for things, either let me know in an upcoming slack thread - or push some changes to this branch
=> Highlights doc for Artsy Engineering

playbooks/support.md
This PR adds two things to the support doc:
- A note about managers covering
- A short list of expectations (tries to make explicit what is explained in greater detail elsewhere)
=> Minor updates to clarify expectations around on-call

.github/ISSUE_TEMPLATE/engineering-onboarding.md
This closes my RFC in artsy/potential requesting a more explicit setup script. I set up a clean install of my personal computer yesterday, so a lot of this is fresh in my head. I added Insomnia and Docker for Mac to the note about installing Jasper, figuring a small list might be good to install while setup scripts run.
Right now I feel like this template is the best home for this documentation- there are several other crannies where one might end up looking while setting up a computer, but assuming we are using this I felt it was the lowest common denominator.
=> Update onboarding + new dev setup notes

events/open-standup.md
Per [this RFC](https://github.com/artsy/README/issues/56), I'm yanking the team lead updates from our open standup.
Closes #61
=> Remove team lead updates

.github/ISSUE_TEMPLATE/engineering-onboarding.md
* Link to slack channels
* Link to project repositories
* Exclude "done" issues from the `good-first-issues` search
* Some other formatting stuff that I didn't do but happened automatically ❔
=> Link-ify some onboarding issue references. Exclude 'done' good-first-issues

.github/ISSUE_TEMPLATE/engineering-onboarding.md
@jonallured helped me create an AWS account, and referenced some instructions on how he did it. It'd be useful to have that link in here, in case someone doesn't know where to find it.
=> Add link for instructions on getting an AWS account created.

playbooks/hokusai.md
* s/rails/node in node example
* Add pointer to set AWS_SECRET_ACCESS_KEY and AWS_ACCESS_KEY_ID in the
quickstart section
=> Update Hokusai's README to use correct version of kubectl

culture/README.md, culture/slack.md, onboarding/README.md, resources/README.md
The `slack.md` doc lists a zillion channels _not_ relevant to work, but not the most relevant ones.
=> @sweir27: List work-relevant slack channels in slack doc

playbooks/engineer-workflow.md
While on-boarding to the @artsy engineering team, I found this rubric by @orta helpful towards determining a team member to assign to a new pull request.
=> Add guidelines towards determining an assignee for a pull request

playbooks/running-lunch-and-learn.md
A couple small updates to the running Lunch & Learn instructions:
- Include Artsy Classroom zoom room permalink
- Rephrase "via Air Display" to "via AirPlay"
=> Update Running Lunch & Learn instructions

events/lunch-and-learn.md
This PR adds some external contributors to our docs from [our Projects board](https://github.com/artsy/README/projects/1).
=> Adds external contributors to L&L docs

events/lunch-and-learn.md, events/open-standup.md, playbooks/running-lunch-and-learn.md
This PR updates our documentation to reflect the new time of Lunch & Learns from [this RFC](https://github.com/artsy/potential/issues/195). I also freshened up our Monday standup docs to fix some formatting problems and old links.
@erikdstock Once this is merged, make sure to resolve the RFC (the docs are [here](https://github.com/artsy/README/blob/master/playbooks/rfcs.md#resolution)).
=> Updates Lunch&Learn time to 12:30

README.md, culture/slack.md, onboarding/engineering-introduction.md, onboarding/managers.md, onboarding/sessions/tour-of-collector-ux.md, playbooks/data-migrations.md, playbooks/engineer-workflow.md, playbooks/extracting-services.md, playbooks/support/README.md, playbooks/technology-choices.md, practices/historical/mobile_2015.md, practices/historical/web_2015.md, practices/historical/web_recommendations_2015.md, practices/platform.md
I like the idea introduced in https://github.com/artsy/README/pull/78 to add a padlock icon next to external links leading to content unavailable to readers outside of the Artsy organization.
I've added that helpful icon to other links in the repository. Probably missed a bunch, but I think this covers most.
=> Add padlock icon next to any link leading to private resources

playbooks/README.md, playbooks/deployments.md, playbooks/engineer-workflow.md
This new playbook is based on the overview of deployment I hosted for onboarding/re-indoctrination. It could go under the "onboarding sessions" you started, but I tried to flesh it out enough to stand alone as a self-service reference so think it might qualify as a playbook.
=> @sweir27: Document deployments

playbooks/README.md, playbooks/documentation.md, playbooks/engineer-workflow.md
It resurfaced today that there's continuing ambiguity about where different types of documents should live. This is an initial stab at describing what might be reasonable "defaults," given our current family of forums and repositories. It also copies some of the discussion about public vs. private content from https://github.com/artsy/README/issues/2.
Closes https://github.com/artsy/README/issues/105.
=> Try to document where documents should go

.github/ISSUE_TEMPLATE/engineering-onboarding.md
Currently it's not obvious who is the mentor for new employees during on-boarding.
Mention the mentor (and kind of remind to pick one) in the issue template.
=> Add Mentor to on-boarding template

.github/ISSUE_TEMPLATE/engineering-onboarding.md
In an effort to connect new engineers, I've added a link the `onboarding-eng` Slack channel and nudge to have new hires :wave: at each other.
closes #76
=> Mention the onboarding-eng Slack channel

.github/ISSUE_TEMPLATE/rfc.md
Sometimes it can be tricky for folks who didn't write the RFC.to know what it takes to resolve an RFC, adding this to the template should make it easier for us to figure it out and state upfront what the end-goal is.
=> Add a note for the resolution step to the RFC template

README.md, conference-notes/2018-11-28-nyc-mobile-forum.md, conference-notes/README.md, conference-notes/summary.json
I attended Facebook's NYC Mobile Forum today and I have some notes.
@bhoggard added some notes [in potential](https://github.com/artsy/potential/pull/204), which makes total sense for the conference he was at, but I think the notes I have are okay to open source. I've added a note to the (new) `conference-notes` readme that points to potential and highlights how it's not always appropriate.
=> Adds conferences notes section, and notes from NYC Mobile Forum 2018

culture/engineering-principles.md
Use relative path, so in case of repo move again, links will still work 😉
=> RFC and retro now live in artsy/README

.github/ISSUE_TEMPLATE/engineering-onboarding.md, practices/README.md, practices/front-end-ios.md
This adds docs for the Front-End iOS Practice, addressing the biggest question: why do we have a separate iOS practice? I followed the format of the [Front-End Practice docs](https://github.com/artsy/README/blob/master/practices/front-end.md) and added what made sense for us.
I'm going to leave this PR unassigned and leave it open for a while, RFC-style. Take your time providing feedback.
=> Adds Front-End iOS Practice docs

playbooks/dependencies.md
Added the words "the" and "to" in order to make a sentence easier to read. Small spelling change of "re-asses" to "re-assess". Done for readability, without trying to change the meaning or style. The line break changed location in order to accomodate the preferred line width.
I've read CONTRIBUTING.md, and hopefully this is a welcome PR despite not working at Artsy 😄 I appreciate you all sharing the well-written playbook on this topic!
=> Fix minor typos in dependencies playbook

playbooks/engineer-workflow.md
This includes the documentation update promised in  https://github.com/artsy/README/issues/109#issuecomment-440395808.
Just wanted to make that concrete. Feel free to wait on that RFC's resolution before merging.
=> Clarify expectation that PRs are only opened when safe to merge and release

culture/peril.md
To handle the migration from a single-repo rule, to a org scoped run: https://github.com/artsy/peril-settings/pull/91
=> Update peril.md to accommodate new global rule

.github/ISSUE_TEMPLATE/engineering-manager-onboarding.md
- Removed references to the first external engineering manager.
- Updated relative links to README to be absolute links since the issues will be a part of potential.
=> Removed references to the first engineering manager onboarding.

culture/slack.md
We value having a diverse engineering team. Elevating where we have conversations around this is important, so let's show new folks where to find it.
=> Added #dev-ersity to the slack channel guide

playbooks/running-lunch-and-learn.md
Fixed the relative link but did not do a local rebuild to confirm that the generated output is correct, I had an issue with my local typescript install that I can look at tomorrow.
=> fix path for event link

playbooks/support/README.md, playbooks/support/responding.md, playbooks/support/scheduling.md, resources/README.md
- Extract "Responding to an Incident" to a separate document
- Move scheduling-related documentation to the scheduling doc
- Clarify on-call staggered rotation process
Paired with @ashfurrow on these updates during today's Writing Office Hours :+1:
=> Update support document

.github/ISSUE_TEMPLATE/engineering-onboarding.md
I found the Engineer Workflow doc very helpful for better understanding how we use GitHub and other services. Also noticed that there were a lot of links to artsy/README docs, but no general link to artsy/README itself - thought it worth calling out.
=> Adds to onboarding: general artsy/README callout, Engineer Workflow doc

playbooks/kubernetes.md
Update docs with some notes about Kubernetes operations
- Using `kubectl` to interact with clusters
- Sshing into a node and debugging with system tools
- Draining and replacing problematic nodes
=> update Kubernetes docs for operations

playbooks/graphql-schema-design.md
From memory and collection from online snippets of our discussions here and there.
=> [GraphQL] Document `camelCase` over `snake_case` convention.

playbooks/support/responding.md
Per our discussions as we're preparing the training, I hope this clarifies that addressing non-incidents is part of the `Assess` phase, not the `Monitor` phase.
=> Update Monitor section of responding doc

playbooks/README.md, playbooks/support/README.md, playbooks/system-criticality.md
This adds some minimal explanation of how we think about system criticality, based largely on https://github.com/artsy/README/issues/176.
The expectations (also copied from the RFC's examples) are meant as placeholders until we can assign systems and figure out what is practical and possible.
=> Document new framework for system criticality

events/open-standup.md
This commits provides a link to view open RFCs on GitHub in our Engineering open standup script.
=> Add link to open RFCs on GitHub to Engineering open standup script

.github/ISSUE_TEMPLATE/engineering-onboarding.md
Minor addition to onboarding checklist: suggest that people list their Github and AWS usernames on their Slack profiles. (Everything else is just `prettier`.)
This helps with [PLATFORM-1225](https://artsyproduct.atlassian.net/browse/PLATFORM-1225) and I've already added these fields to our org's profile template.
=> Suggest that people add Github and AWS usernames to their Slack profiles

playbooks/engineer-workflow.md
Following up on [RFC 177](https://github.com/artsy/README/issues/177), this PR updates documentation around PR standards at Artsy. It will be followed by a pair of Peril rules, one that warns if > 1 person is assigned to a PR, and one that adds a comment 1 business day after someone is requested to review if they have not yet reviewed.
Let me know if you have any feedback!
=> Update engineering workflow document with new PR role definitions

playbooks/engineer-workflow.md
@dblandin noted that the initial updates made [to this doc](https://github.com/artsy/README/pull/195)  included an unhelpful definition of code review - for now I've simply generalized the code review requirements, and I think a future RFC around code review is an excellent idea.
Thanks for the thoughtful feedback!
cc @joeyAghion - thanks for helping to clarify the assignee/reviewer designation!
=> Improve language around what code review + assignment entail

playbooks/running-lunch-and-learn.md, resources/lnl.md
Historically, we've archived Lunch & Learn recordings in a Dropbox folder shared only with the Engineering team. While Engineering is responsible for organizing and running Lunch & Learn, all Artsy
employees are welcome to attend and we often host non-technical talks from internal and external speakers.
We've recently created a new Lunch & Learn folder, visible to anyone at Artsy, and copied past Lunch & Learn recordings over.
This commit updates the Running Lunch & Learn playbook to mention and link to this new folder location.
Post merge, I plan to remove the old folder from the Artsy Engineering Dropbox folder and communicate this change with the rest of the Engineering team.
=> Update Running Lunch & Learn doc with new Dropbox folder location

events/README.md, events/lunch-and-learn.md, events/show-and-tell.md
After some chatting on Slack:
https://artsy.slack.com/archives/C9ZUJE65V/p1557411649003100
We're looking to use the L&L time slot for both events and alternate weeks.
h/t @alloy for the nudge here!! ❤️
=> Update docs for merging S&T and L&L

events/open-standup.md
Those events have been "merged" so I'm altering the item in open standup to reflect that. @ashfurrow does this seem right?
=> Update item for L&L and S&T

README.md
This PR adds a footer to the README.md file to highlight some aspects of the Artsy Engineering Brand, specifically:
* the blog
* our Twitter account
* Artsy public API
* careers page
Here's how it looks:
And you can see it live here:
https://github.com/jonallured/README/tree/add-footer
I've seen this done before, here are a few examples:
https://github.com/hashrocket/decent_exposure#about
https://github.com/thoughtbot/factory_bot#about-thoughtbot
I have aspirations of copying this to all our open source repos, but wanted to start here and nail the copy, etc.
=> Add a footer to highlight Artsy Engineering

events/open-standup.md
Front end office hours have officially been rolled into the front end practice time.
=> Remove FE office hours

events/open-standup.md
This adds a section to mention the running peer learning groups during engineering open standup.
=> Add running peer learning groups to open standup

playbooks/support/README.md, playbooks/support/on-call-slo.md, playbooks/support/responding.md
I've had to raise a couple incidents this week, and noticed that we didn't have all our README docs updated from our transition to OpsGenie. This PR addresses that.
=> Update on-call docs based on our transition to OpsGenie

playbooks/hokusai.md
I only changed 2 lines. As usual prettier has its own plans.
=> Document how to isolate Gravity's and Metaphysics' cache spaces among review apps and staging

practices/front-end-ios.md, resources/mobile/README.md, resources/mobile/summary.json, resources/mobile/xcode.md, resources/tech-learning.md
This PR adds a basic knowledge base for developing iOS software at Artsy, which came out of our Front-End iOS Practice meeting this morning ([notes are here 🔐 ](https://www.notion.so/artsy/July-19-2019-Meeting-Notes-12000fc88fa1480997fb3ac0e7375f04)). The goal is to provide a place where we can accumulate knowledge of how to build iOS software, specifically iOS software at Artsy.
It is a work-in-progress; I've purposefully left some TODO comments to give others a jumping-off point to add their own resources. I couldn't help adding links to docs and blog posts that I think are important, though 😄 The most nebulous section is, and will be, how+why to use Objective-C as a React Native developer. Really exciting times!
=> Basic structure of mobile knowledge base

careers/ladder.md
This will allow us to deprecate the duplicative notion doc!
I used html because the markdown syntax was getting pretty unwieldy given how involved the lines are.
=> Converts capabilities into a matrix form

playbooks/support/responding.md
The workplace team recently provisioned a Pro Zoom account for use
during incident response. This Pro account is not limited to a 40 minute
max duration of calls.
=> Add item to start a video conference in On-Call docs

events/open-standup.md
- Re-order milestones Engineering Standup section to match agenda  …
Noticed this morning that the section order in the notes template didn't match the section order in the agenda.
- Condense items in Engineering Standup agenda
Reduce the verbosity of the Engineering Standup agenda items so they can be more easily scanned during the meeting.
=> Update Engineering Standup agenda + notes template

resources/tech-learning.md
This PR links to our iOS Learning Group in Notion, as well as the iOS learning scaffold. (This scaffold will eventually hold the materials from our iOS Learning Group, as we build+deliver them.)
=> Adds links to learning resources

events/open-standup.md
This PR updates our standup instructions. Here's the summary:
- **Remove the agenda**. We should use the template as the agenda, to avoid having to keep two lists in sync.
- **Adds follow-up note** to review these docs and update them as needed.
- **Links to a blog post** explaining the philosophy of our standup.
- **Removes support handoff** since this is happening in a staggered way and is covered by our support docs. In practice, we were never doing this anyway, so we should remove it from the agenda.
- **Removes reminder of incidents** in pre-meeting instructions. The people running the meeting are on-call and probably don't need to remind themselves; we could update the Peril message to remind them if we need to.
- A few other cleanups, like moving to the Annex and telling the …
=> Cleans up standup instructions

resources/mobile/learning-group/session-two.md
I think this helps clarify some of the module resolution, and adds a simpler example ahead of `EntityHeader`. I think this better addresses some feedback that @xtina-starr left on #254, too.
=> Adds more info about Box and div

onboarding/engineering-introduction.md, onboarding/managers.md, onboarding/sprint-rotation.md
* Fix a few links
* Add new links to #dev-help, blog post on code names, domain models, hokusai, and the onboarding calendar.
* Recommend at least 3 rotations of 1 sprint each.
* Recommend nominating a "pairing partner" in each team. This ends up happening anyway or just falling to the technical lead. Better [I think] to encourage pairing and ensure a buddy is available in each rotation.
I struggled to locate a good link that would list teams (including future ones, once they exist) and ideally link to each of those teams' docs, but [this](https://www.notion.so/artsy/Product-470238180cf94c87906ef1d3ee259e05) was the best I could find (and it was pretty out-of-date). Am I missing a better alternative? Or is this another thing that has to wait for the one true documentation repository 🙏 👼 🙏 …
=> Update sprint rotation recommendations

playbooks/cloudflare.md
Follow-up to Dyn -> Cloudflare migration. See https://artsyproduct.atlassian.net/browse/PLATFORM-2012
=> remove Dyn from Cloudflare playbook

practices/front-end-ios.md
I'm going to remove the old Slack user group now, as well.
=> Removes references to the App Release Team, updates release notes

events/open-standup.md, playbooks/technology-choices.md
Several of us were recently discussing how to ensure technical plans surface the most relevant feedback. It's not always obvious who may have worked on a problem in the past (including in past teams/roles) or have other important insight or context.
**Proposal 1:** We already mention RFCs at big stand-up. I think it's appropriate to also mention any active technical plans. This ensures engineers outside of a given team or slack channel hear about significant changes and have the opportunity to offer feedback or attend the review discussion. If there end up being too many (or too minor) plans mentioned at this opportunity, we can revisit this.
**Proposal 2:** I updated the doc's language to recommend a review discussion (even a brief one) more strongly. I _don't_ want to create additional …
=> [RFC] mention tech plans at stand-up and recommend review discussions

playbooks/migrating-redis.md
Migrate Redis playbook using our [redis-migrate Docker image](https://github.com/artsy/docker-images/tree/master/redis-migrate)
=> add migrating redis playbook

culture/what-is-artsy.md
This article links out to The Verge and it produced a GitHub 404 error for me.
=> Fix broken link

events/artsy-learns-to-code-v2.md
I know we're a ways out yet, but I wanted to add Glitch resources to the docs. The p5js.org resources are great, and Glitch makes a great addition by giving access to a richer editor, node module integration, hosting, and a social remixing capability that I'm quite fond of. I've linked to a p5js team on Glitch with a bunch of starter projects, too.
=> Adds p5 Glitch to learning resources

playbooks/README.md, playbooks/migrating-redis.md, playbooks/migrating-sidekiq.md
To keep the README repo consistent, we run a few scripts using a git commit hook (installed through [Husky](https://github.com/typicode/husky) upon `yarn install`). These scripts generate a table of contents based on YAML frontmatter, as well as running docs through Prettier. My guess is these docs were created+edited without having run `yarn install` in the repo.
This is only an issue because, while working on #294, I had the following added to my commit:
```diff
diff --git a/playbooks/README.md b/playbooks/README.md
index 79c43c2..30f6225 100644
--- a/playbooks/README.md
+++ b/playbooks/README.md
@@ -33,6 +33,8 @@ practice should be incorporated, submit a PR!
| [How to give a good Informational](/playbooks/informationals.md#readme) | What are the steps needed to give someone a great …
```
=> Adds description for Redis+Sidekiq docs, applies Prettier

careers/ladder.md
We’ve decided to update our engineering level titles to match better our values and our hiring practice. We are not changing the expectations of each level.
Associate Engineer is now called Engineer 1. “Associate” is a common term for entry-level roles. Our hiring practice is more open to people with different backgrounds and level of professional experiences (even if they switched recently to a software engineer role). We feel that Engineer 1 reflects better their role rather than ”Associate Engineer”.
Engineer level is now called Engineer 2 to reflect this progression.
All the other titles are left unchanged.
=> Update ladder titles

playbooks/migrating-postgres-with-rubyrep.md
Playbook for migrating Postgres databases with [Rubyrep](http://rubyrep.org/) using our [Docker image](https://github.com/artsy/docker-images/tree/master/rubyrep)
=> add playbooks/migrating-postgres-with-rubyrep.md

playbooks/migrating-postgres-with-rubyrep.md
=> fix typo in playbooks/migrating-postgres-with-rubyrep.md

events/open-standup.md
Given that frontend practice has moved to an ad hoc meeting basis, let's remove the updates from the standup notes.
=> Remove frontend practice updates

events/open-standup.md
Removing outdated (and unnecessary) title call out in agenda.
Company Updates should be sufficient.
=> Update standup agenda

playbooks/agile/team-working-agreement.md
During the team working agreement brainstorm for the consignments team, we had an item that required further discussion because it wasn't universally agreed upon. This PR adds a line item to the team working agreement walkthrough to make sure these things get talked about instead of ignored.
=> Clarify that teams should take time to discuss TWA items they didn't write

playbooks/hokusai.md
We discovered that, as @pvinis does _not_ connect to `us-east-1` by default, some strange Hokusai behavior materialized.... namely Hokusai was looking for the ECR registry in the wrong region, and like S3 buckets, there are scoped to a single region.
=> update Hokusai playbook required AWS environment variables

.github/ISSUE_TEMPLATE/dependency-rfc.md, playbooks/README.md, playbooks/technology_radar/artsy-tech-radar.csv
@sweir27 This is a follow-up from our conversation in #307. I've added inline HTML comments to the RFC markdown template so that the engineer opening the issue will see them in their issue-compose text input, but they won't be visible in the rendered markup. This is a technique I'm borrowing from [fastlane](https://raw.githubusercontent.com/fastlane/fastlane/master/.github/PULL_REQUEST_TEMPLATE.md).
I've tried to clarify the point of the checklist, as well as the RFC process itself. Happy to further amend based on feedback. There is some file churn from the pre-commit hook as well.
=> Updates new dependency RFC template

playbooks/technology-choices.md
As discussed in https://github.com/artsy/README/issues/310, let's stay lightweight in how any overhead impacts new projects. This mostly reiterates our usual recommendations, but:
* adds an explicit FAQ to remove ambiguity about new projects, and
* shortens a few other sections for easier reading
Closes #310.
=> Clarify recommendations around starting new projects

playbooks/hokusai.md
Update to Hokusai doc.
- Made `Configure Hokusai` a higher level heading.
- Removed `Configuring access to Kubernetes` section. It's content is already covered by `Configure Hokusai`.
=> Remove redundant section on hokusai configure.

README.md, culture/engineering-principles.md, hiring/README.md, hiring/interviewing.md, hiring/summary.json
This PR adds a document on our interview process! The goal is for this to be public and kept up-to-date so we can share with candidates before and throughout our interview process.
This builds off of a working session with @jonallured and @xtina-starr ✨ and is influenced by [this awesome blog post](https://artsy.github.io/blog/2019/01/23/artsy-engineering-hiring/) from Artsy engineers and [this other awesome blog post](https://jvns.ca/blog/2020/06/30/tell-candidates-what-to-expect-from-your-job-interviews/) about the importance of being transparent in interviewing.
=> Adds doc on interviewing

README.md
We've been including the "About Artsy" section in README in public repos. However, some links are _relative_ so they break in other repos. This turns them into absolute links so copying and pasting still works.
=> Make About Artsy links in README absolute

playbooks/deployments.md, playbooks/support/README.md
This doc was last updated during the early part of our transition to more consistent CI and release tooling. Happy to say we can drop most of it finally, and instead point readers (new engineers, especially) to the templates and tools that will mostly do the right, standard thing.
Depends on doc updates pending in https://github.com/artsy/horizon/pull/221.
=> Update deployments playbook to reflect more consistent process and mature tools

playbooks/engineer-workflow.md
Following an [RFC](https://github.com/artsy/README/issues/309) and much discussion, we are now working in branches on the main repo instead of forks.
=> fix: change from forking to branching on main repo

playbooks/engineer-workflow.md, playbooks/support/README.md, playbooks/technology_radar/artsy-tech-radar.csv
Tiny change, big write-up.
Building and maintaining our shared GraphQL orchestration layer ([Metaphysics](https://github.com/artsy/metaphysics)) has been a growing challenge, especially as multiple teams have tried to extend and release it safely across independent work streams. The Platform practice has been considering the alternative [Backends for Frontends](https://www.thoughtworks.com/radar/techniques/bff-backend-for-frontends) pattern that addresses some of these challenges by separating more focused back-ends for each product or product area. After lots of thinking and discussion, I propose that we **hold** further consideration of that pattern and instead rededicate ourselves to making our shared service and schema as powerful and robust as possible.
* BFFs optimize for long-lived …
=> [Radar] "Hold" Backends for Frontends in favor of a unified GraphQL schema

playbooks/engineer-workflow.md
Our shared repositories have started accumulating crufty branches since https://github.com/artsy/README/issues/309. Automatically deleting merged branches helps, but there's still the potential to accumulate branches from works-in-progress or abandoned work streams, and even the potential to conflict on common names.
Let's recommend the convention of `<github_user_name>/<topic>`. This is the nicest pattern I've seen, among others like `<user>-<topic-...>` or `<jira#>-...`.
=> [RFC] Recommend naming working branches like <github_user_name>/<topic>

playbooks/engineer-workflow.md, playbooks/support/README.md
Teams (and individuals) have been experimenting with adding more clarity around their PR comments. Most recently, this manifested in some teams trying out [Conventional Comments](https://conventionalcomments.org) guidelines.
However, it can be jarring or confusing to see conventional comments-style code review labels without explanation. See discussion (and the impetus for this RFC!) in [this slack thread](https://artsy.slack.com/archives/C02BC3HEJ/p1598380026075800).
While I don't believe we need to require code review comments to follow any particular standard format at this time, I do think it would be helpful to reference Conventional Comments and provide some suggestions for quality code reviews.
If we find that code review comments are consistently low-quality or causing confusion, …
=> RFC: Adds suggestions for Code Reviewing

resources/lnl.md
Since we've migrated over to Google Drive, the Dropbox links were broken. I'm pretty sure the links I used would work for anyone at Artsy but we should double check. (Could also consider adding a few more highlights from the archive in a future PR since there are so many good ones!)
=> Replace Dropbox links with Google Drive links on Lunch & Learn highlights page

onboarding/mentors.md
This PR simplifies our mentorship doc to outline a single kind of engineering mentor- the 'onboarding mentor' role. I think it would be good to get feedback from others on the team, including anyone planning to start as an onboarding mentor or upcoming hires.
I think we should still radically trim or remove the 'hypothetical agenda' section in favor of a shorter menu of possible activities.
No significant changes from 'your first week' down - this is just prettier formatting text by # of columns.
=> clarify ONBOARDING MENTORS role

careers/ladder.md
There's more context than can/should fit into this PR description (please refer to the accompanying Google doc for more detail!).
At a high level, we’ve decided to update the language of our engineering ladder in order to make it a more useful tool for all of us.
This PR includes a few changes to the ladder's content:
1. The descriptions for each level have been clarified for greater specificity.
2. Senior Engineer is now explicitly two levels, with corresponding criteria.
There are also a few changes to general formatting/structure of this document:
1. A `tl;dr` section, extracted from the previous ladder iteration, to capture a "one-liner" for the scope and impact of each level.
2. The ladder is now organized by "capability" and formatted in a way to clearly show the progression through …
=> Feature: Updates to our Engineering Ladder

playbooks/support/responding.md
This PR updates our documentation for responding to incidents so that engineers are instructed to write postmortems for all incidents, regardless of severity.
=> fix: update documentation for resolving an incident

playbooks/rfcs.md
Update the RFC docs and templates to include an explicit section on ~(1) how an RFC will be implemented and (2)~ how an RFC is resolved. This section should be a precise description of how we'll know when the proposal has been accepted.
The goal of this RFC is to drive more clarity about the implementation and resolution of RFCs. Clearer guidelines around implementation and resolution will allow team members (especially newer members) to contribute more easily to the RFC process.
~While in practice we do include implementation plans for RFCs adding this section to the template makes it explicit and serves as a reminder to think about how to roll out the proposal. This is especially important for changes that have large scope and might require broader feedback and alignment to fully …
=> RFC: Add sections explicitly outlining RFC implementation and approval to the RFC template and documentation

playbooks/support/scheduling.md
This update to the docs introduces the artsy cli command for listing engineers for the on-call rotations. It's a little sparse on getting things all setup but that sorta seems outside the scope of this doc ya know? Anyway, this is better than nothing and we can continue to improve.
=> Mention the artsy cli command

onboarding/managers.md
The link is in the sprint rotation doc, but I figure it helps to mention here, too.
=> Link to onboarding calendar from manager onboarding checklist

.github/workflows/mondayInformationals.yml
Use the Artsy CLI and scheduled GitHub actions for our Monday Informationals.
Currently in-progress. This doesn't support all of the Peril-backed tasks yet.
#FF #FutureFriday
**Example**
=> feat: run standup reminder via @artsy/cli every Monday at 9am ET

.github/workflows/monday-informationals.yml
This workflow was pinned to the alpha NPM tag while https://github.com/artsy/artsy-cli/pull/24 was still open.
We can use the stable channel now.
=> feat: update monday informationals to use @artsy/cli stable version

practices/README.md
Oops, this link got removed with `scripts/create-readmes.ts`, add link outside of TOC autoformatted table.
=> docs: Add playbook on practices

playbooks/README.md, playbooks/development-environments.md
This documents a convention for set-up and configuration that we've been trying to refine over several iterations in [Horizon](https://github.com/artsy/horizon/pull/177), Gravity ([1](https://github.com/artsy/gravity/pull/13345), [2](https://github.com/artsy/gravity/pull/13372)), [Volt](https://github.com/artsy/volt/pull/4582), and [Metaphysics](https://github.com/artsy/metaphysics/pull/2765).
The _aspiration_ is that setting up a new development environment is turn-key, and there's a shared, up-to-date place to put any configuration necessary for development.
**Whether to automate setup at all.** There's been a lot of discussion recently about whether project setup should be standardized and automatic or tailored and manual. Long term, containerized environments should solve this, but I …
=> RFC: Propose conventions for project set-up and configuration

playbooks/engineer-workflow.md
As mentioned in [artsy.github.io#650](https://github.com/artsy/artsy.github.io/pull/650#issuecomment-793921467), this PR adds a couple links to our recent blog articles on pull requests.
=> feat: Add links to PR articles

onboarding/sprint-rotation.md
Updating relevant locations to link to new team process handbook (currently includes Notion, Potential, and README).
=> Link to team process handbook in context of sprint rotations

playbooks/kubernetes.md
The links to the hokusai documentation were broken. Relative links in Github markdown can reference simply the file name without slash or the meta folder. This is described [here](https://github.blog/2013-01-31-relative-links-in-markup-files/).
=> fix relative link to hokusai docs

onboarding/engineering-introduction.md
Have added Future Friday's to the engineering introduction doc. This addresses the issue of FF not being mentioned in the onboarding docs. In addition, a section on Project Management / Sprints has been added (this sections mirrors what is in [Engineering Workflow](https://github.com/artsy/README/blob/master/playbooks/engineer-workflow.md#project-management) but the section is short, and is logical to have in both places, so don't believe the duplication to be an issue.
=> feat: update engineering introduction with future fridays and sprints

practices/README.md
The current link to "_the Practice Playbook_" is returning a [404](https://github.com/artsy/README/blob/master/practices/playbook.md#readme). This updates the path to point to the [correct location](https://github.com/artsy/README/blob/master/playbooks/practices.md).
=> Update playbook path in practices readme

playbooks/deployments.md
- The section in CircleCI project settings to add additional SSH key is now named `Additional SSH Keys`.
- Add a note advising to not delete the default read-only key.
=> fix: update circleci key setup steps.

practices/mobile.md
Fixed broken link to the artsy omakase in practices/mobile.md
You can find more context in [issue 394](https://github.com/artsy/README/issues/394)
=> fix: update link to the artsy omakase

playbooks/engineer-workflow.md
This updates our PR section with concise instructions on how / when to use the `assignee` / `reviewer` fields.
=> docs: [engineer-workflow] Update PR section with TLDR on assignee / reviewer responsibilities 

playbooks/support/responding.md
This PR fixes a broken link to the artsy status page.
=> fix: link to status page in support playbook

events/open-standup.md
Noticed while running today's standup that we could benefit from a prompt for new episodes, esp. since we've been so prolific lately.
=> Add a prompt for new podcast episodes

culture/slack.md
Small PR to add the postcards channel to the slack list of other topics channels
=> docs: Adding the postcards channel to the slack list of other topics

onboarding/sprint-rotation.md
- Switching to the onboarding notion page, since the onboarding calendar is deprecated
- removing some extra white spaces
=> Deprecating the onboarding calendar: switching to the Notion page

playbooks/technology_radar/artsy-tech-radar.csv
Adopt Swift over Objective-C for the fairly narrow but important use case of native features that cannot be written in react native or cannot be written in react-native without compromising user experience.
**Major caveat:** we should still prefer react-native whenever possible. 
- Swift is what Apple's docs, development and guidelines prefer
- in general the iOS communities knowledge base has largely moved to Swift
- Swift is more beginner friendly and familiar for devs coming from modern languages
- more familiar syntax than SmallTalk based Objective-C with message passing
- Swift code has less boilerplate
- Modern language features are rolling out to Swift 
- https://docs.swift.org/swift-book/LanguageGuide/Concurrency.html
- Swift is type safe and null safe and fits with our general …
=> RFC: Adopt Swift for new native feature work over Objective-C

playbooks/README.md, playbooks/rename-master-to-main.md
Doppler's switch to use `main` (https://github.com/artsy/doppler/pull/218) was straightforward, but revealed some further steps that will be necessary when updating deployed systems.
(Please ignore the unrelated prettier-forced updates.)
=> Add steps for migrating deployed systems to use the main branch

playbooks/rename-master-to-main.md
Adds [lattice](https://github.com/artsy/lattice) to list of repos that master was renamed to main
=> docs: Add lattice to list of repos that master was renamed

playbooks/rename-master-to-main.md
While we were in the FF Berlin Mob inclusive language zoom call we were discussing about updating the CI and docs before updating the actual branch since the open pr might take some time before getting approved, so I am moving that up on the steps of renaming master to main.
=> docs: Update rename master to main docs

playbooks/open-sourcing.md
https://artsy.slack.com/archives/CA8SANW3W/p1642710084260500
I am following the instructions in this doc to open source [ops-util](https://github.com/artsy/ops-util) repo. Came across the section on scanning a repo for secrets. Want to add `trufflehog` for scanning commit history.
=> feat: update info on secrets scanning

playbooks/deployments.md
=> fix: Add working link for deploy blocks

onboarding/README.md, playbooks/technology-choices.md, playbooks/technology_radar/artsy-tech-radar.csv
There's been a lot of interest in feature-flagging and split-testing recently. A few trials of specific tools are in intermediate states while we evaluate or unwind them, so let's make that more clear in our tech radar. Specifically:
* **Trial Unleash for feature-flagging and split-testing**. Support has been added to 2 back-end systems so far, and work is in progress (or planned) to integrate it into clients like Force and Eigen. Integrating into multiple clients is worthwhile despite not yet being fully "adopted," because how the service operates across the platform and stacks is an important element of this evaluation. There's some risk of wasted work, but little long-term maintenance burden because client SDKs fall back to defaults when the service is unavailable. <Debate...?>
* …
=> Propose Unleash trial (for feature-flagging and split-testing) more formally via radar

playbooks/incident-handling.md
Added a line to close alerts as part of incident management.
=> docs: update incident-handling playbook - close alerts when incident is over

package.json, playbooks/README.md, playbooks/future-friday.md
Describe Future Friday within PDDE at Artsy and link to some related resources like the [RFC](https://github.com/artsy/potential/issues/146 artsy/potential.
cc/ @jonallured @evaschilken @joeyAghion
=> feat: Add page documenting Future Friday

resources/tech-learning.md
Add egghead.io (add access info) to tech learning resources.
cc/ @damassi @jonallured
=> docs: add egghead.io to tech learning resources

playbooks/hokusai.md
https://artsyproduct.atlassian.net/browse/PLATFORM-4009
Point to Potential setup script which installs a specific version of `aws-iam-authenticator`.
=> fix: aws-iam-authenticator instruction

onboarding/sprint-rotation.md
Directly calling out the google groups URL for those unfamiliar with how to add themselves to a group
=> Chore: Adding google groups link to the New Engineers responsibilities section

events/README.md, events/knowledge-share.md, events/open-standup.md, events/show-and-tell.md, events/writing-office-hours.md, onboarding/engineering-introduction.md, playbooks/README.md, playbooks/engineer-workflow.md, playbooks/running-knowledge-share.md, playbooks/technology-choices.md, resources/README.md, resources/ks.md, spellcheck.json
Now that we've rebranded **Lunch & Learn || Show & Tell** as simply **Knowledge Share** this updates a bunch of documentation accordingly.
There are still several references/instructions relating to IRL presentations with external speakers. I've updated but not totally removed these, because maybe this will become a thing again someday 🤷🏽
=> chore: update Lunch & Learn references => Knowledge Share

playbooks/hokusai.md, playbooks/kubernetes.md
- Update `kubectl` version.
- Datadog links currently hardcode Kubernetes cluster names which change at every Kubernetes upgrade. Let the links refer to `production` and `staging` so we won't have to change them much.
=> feat: minor update after k8s upgrade

playbooks/dependencies.md
We are currently already using dependabot for automatic library version updates. But we still have to merge every one of these updates manually. Let's use the automerging feature from github actions for these dependabot PRs. We could restrict the automerging to minor version updates (or even to only patch updates). And of course we would allow automerging only to the staging environment and only when CI is green. Also this decision would have to be made repo by repo so projects that are not a good fit for the feature (like Eigen) could be excluded. 
Find implementation details in this [tech plan](https://www.notion.so/artsy/Github-actions-allows-dependabot-auto-merge-when-CI-green-45c5213924064657ae2ba5b40c2960d1).
Most of the dependabot update PRs are trivial and if the CI is green there …
=> RFC: Enable Automerging Feauture for Dependabot PRs

playbooks/engineer-workflow.md
This PR updates the commit section of the engineer workflow description. It supports RFC #327 which proposed [conventional commits](https://www.conventionalcommits.org/en/v1.0.0/) as Artsy's commit message convention and aims to improve adoption across the engineering team. 
Importantly, it also supports ongoing work to track the ratio of new to rework by parsing through commit messages on Artsy Repos. See [relevant slack thread](https://artsy.slack.com/archives/CA8SANW3W/p1656606603284369).
The list of accepted `types` is based on [commitlint](https://github.com/conventional-changelog/commitlint/tree/master/%40commitlint/config-conventional). See [relevant slack thread](https://artsy.slack.com/archives/C02BC3HEJ/p1659976173598959). 
Note: I'll share in #dev before merging, but wanted to …
=> docs: update commit section of engineering workflow

playbooks/README.md, playbooks/technical-planning.md, playbooks/technology-choices.md
This RFC proposes:
- Adding a new document describing our technical planning process. This will be linked to from the existing `technology_choices` document, but since tech plans are about more than just adding new technologies, we feel it warrants its own page.
- Clarification to all steps of our current tech planning process, much of which is implicit. We expect these steps to change over time. This clarification touches topics such as:
- What is a tech plan
- When to write one
- How to write one
- What the possible states are (and how to advance between them)
- How to choose stakeholders
- How to provide feedback and approve a tech plan
- Consolidating a few fields on the template:
- `Contributors` and `Champions` will be removed, replaced by a single field “Author(s)” so that it’s …
=> RFC: Adds Technical planning document

playbooks/documentation.md
https://github.com/artsy/README/issues/492 prompted me to take a look at our existing documentation playbook covering some of the same topics. I had failed to update it when we decided that _Notion_ would be a preferable location for internal documentation instead of the Potential repo.
=> doc: Update documentation playbook to reflect transition from Potential to Notion

playbooks/technology_radar/artsy-tech-radar.csv
Inspired by https://github.com/artsy/README/pull/501, let's clarify ruby's "adopt" status, especially for data-backed APIs and services.
We have many ruby back-ends and significant built-up experience maintaining and evolving them. (The only exceptions I can think of are Positron, Causality, and APRD, which are unmaintained or deeply out-of-favor.) It should be the default option for any new back-end needs.
=> doc: clarify ruby's adopt status

playbooks/technology_radar/artsy-tech-radar.csv
In recent discussions around an [Opstools PR](https://github.com/artsy/opstools/pull/12), we noticed that the Tech Radar has no entry for Python. It seems we should add such an entry, because there are significant [repositories with Python code](https://github.com/orgs/artsy/repositories?language=python&q=&sort=&type=all), Hokusai/Motion/Zenith being the main ones.
The `description` field for the entry is left blank, to be filled in based on discussion in this PR, therefore, the PR is tagged `Draft`.
=> fix: add Python as it has been in use in various repos.

playbooks/development-environments.md
As discussed, let's consistently advise _reviewing_ setup scripts, and running them or the _equivalent_ steps for one's environment.
=> Suggest README language around setup scripts

playbooks/deployments.md
`hokusai production deploy <tag>` updates Kubernetes `Deployment` resources only, which is insufficient for  
[Incident 170](https://artsy.slack.com/archives/C04RN72NARG) where we have to revert `Ingress` (in addition to `Deployment`).
Let the doc mention `--update-config` which can be used to update all Kubernetes resources defined in `production.yml` spec.
=> feat: mention hokusai update-config flag for deployment rollback

README.md, RFCs/README.md, _templates/README.md, playbooks/README.md, playbooks/engineer-workflow.md, playbooks/technology_radar/artsy-tech-radar.csv
This is a follow-up to [this Slack discussion](https://artsy.slack.com/archives/C02BC3HEJ/p1684515632728489) in which we noted the need to update guidance around Pull Requests by:
- clarifying some ambiguities
- acknowledging current team practices
(Ignore the reformatting in the first commit; the substantive changes are in 39bfd8b5988423d3022255070784ca44cc6349b2)
=> docs: update guidance on pull requests

.github/ISSUE_TEMPLATE/rfc-template.md
Unless I'm missing something our issue template for RFCs does not work anymore. I searched for GH docs and it appears they want these templates in `.github/ISSUE_TEMPLATE/` so I used their builder to create what you see here. I just copy/pasted from the `_templates/rfc.md` file so it should be a match.
=> Add RFC Template

.circleci/config.yml
https://artsyproduct.atlassian.net/browse/PHIRE-82
This switches the CI pipeline to read _danger github token_ from circleci contexts.
Migration:
=> chore: use danger-github-oss context

events/open-standup.md
Removing Hiring Updates and Welcoming New Members from the stand-up agenda since we are not hiring extensively now. We could bring them back when needed. Meanwhile, if there are Hiring Updates, we will use the Company Updates section to mention them.
=> Remove hiring updates from open-standup.md

playbooks/development-environments.md
This PR updates our docs to specify asdf as the preferred version manager over rbenv and nvm.
=> Update prerequisites to use asdf

playbooks/technology_radar/artsy-tech-radar.csv
Added `adopt` to next, and the word "should" in the description! Thoughts?
=> docs(tech-radar): Add Next.js to the list

playbooks/technology_radar/artsy-tech-radar.csv
Given the most recent attempt to migrate Volt 2 to Next 13's app router, felt we should move this back to Trial. Thoughts on this can be [read in this Slack thread](https://artsy.slack.com/archives/C2TQ4PT8R/p1697227679293829).
TLDR: Next.js pages router works great for us, without gotchas or perceivable problems. Yet, moving to the new app router involves a lot of friction. To recommend Next.js as `Adopt` would, I think, _also_ imply that we're on board with Next.js 13's new router, react server components (RSC) and more. 
As adopting this would come at a significant cost to Artsy due to Palette not being compatible (Palette requires a JS runtime to function), this should give us pause. Moving from `Trial` -> `Adopt` requires more discussion.
=> docs(tech-radar): Move Next.js from 'Adopt' to 'Trial'

playbooks/cloudflare.md
Delete the section of "Routing requests around Cloudflare".
Discussed with @joeyAghion. We don't see ourselves routing requests around Cloudflare.
=> feat: delete Routing requests around Cloudflare

playbooks/development-environments.md
Back in https://github.com/artsy/README/pull/368, I proposed a convention for storing shared configuration for development environments in S3. That convention has been working, but I regret choosing the particular path (`artsy-citadel/dev/.env.<project>`) for a few reasons:
* It requires renaming the file as part of the `aws s3 mv` operation. This misses an opportunity for the file to self-document how it should ultimately be named. It also creates confusion (when it's copied down with its original name, or when a `.env.shared` is mistakenly copied up to S3).
* It doesn't accommodate multiple files, which a few projects (Vortex, Eigen, Infrastructure, Energy...) have needed.
Instead, I think we should source shared config from paths like `artsy-citadel/<project>/.env.shared`. Projects …
=> doc: update preferred S3 path for shared configuration

playbooks/documentation.md, playbooks/open-sourcing.md
Minor additions to:
* Link our open-sourcing playbook to the other playbook's guidelines for public vs. private content
* Mention the additional case that came up with respect to Volt-v2, of code repositories that aren't necessarily sensitive themselves but benefit from the safety of private discussion
=> doc: link and expand open-source guidelines

events/open-standup.md
Just keeping our public version of this in sync with [the change](https://artsy.slack.com/archives/C02BC3HEJ/p1711989001006189) we made in Notion
=> chore: remove peer learning group section

playbooks/development-environments.md
Small change to help stave off the chance of values in `.env.shared` files getting clobbered in the event a developer needs to update them.
=> docs: nudge devs to avoid clobbering .env.shared
