- README.md
- best-practices/README.md
- culture/README.md
- events/README.md
- events/open-standup.md
- package.json
- playbooks/README.md
- playbooks/running-lunch-and-learn.md
- practices/README.md
- practices/historical/web_recommendations_2015.md
- recommendations/README.md
- scripts/create-readmes.ts
- tsconfig.json
- some minor TypeScript faff
- some typo fixes
- adds the web 2015 recommended reading guide, useful for knowing past recommendations
- migrates some of the final PRs to meta/guides/potential
> Adds some archival pages, defaults TOC links to the README

- playbooks/being-an-artsy-engineer.md
- recommendations/blog.md
Tries to add context to what question the blog post answers
> Fleshes out the blog post recommendations

- .github/ISSUE_TEMPLATE/engineering-onboarding.md
Based on feedback from https://github.com/artsy/README/pull/4, adds the onboarding checklist as an issue template.
> Adds onboarding template

- .github/ISSUE_TEMPLATE/engineering-onboarding.md
- README.md
> fixes some links in the issue template

- playbooks/rfcs.md
👋 - I know it's a bit weird to a do a fly-by PR, but 🤷‍♂️ 
Was just perusing the README and noticed what I think is a small grammar error.
> Typo: Of -> If

- .github/ISSUE_TEMPLATE/engineering-onboarding.md
Add checkbox item: _"Download [Jasper App](https://jasperapp.io/); this will help you manage Github interactions. "_
> [Onboarding] Add checkbox item for Jasper

- .github/ISSUE_TEMPLATE/engineering-onboarding.md
I don’t know if the previous version was in the copy given to @ansor4, but in my introduction chat with him I felt the need to express that _any_ doc changes are great changes.
Open to suggestions for rephrasing it!
> [onboarding] Put emphasis on encouragement to PR doc changes.

- .github/ISSUE_TEMPLATE/engineering-onboarding.md
- onboarding/README.md
- onboarding/managers.md
- onboarding/sprint-rotation.md
This is a new thing, but here's a doc that we can iterate on!
> Adds doc on what the sprint rotation is, how it works

- practices/platform.md
- recommendations/README.md
- recommendations/tech_learning.md
This is meant to be the start of a single README page for Tutorials We Love- an answer to the question 'Hey, I'm looking at picking up some work in [new language/paradigm/domain]- where should I start?'  I chose headers focused on languages and practices, with links in between them. I've compiled some that I picked up from looking around and will add more, but requested changes to this PR itself are also welcome!
> Add tech learning page

- events/open-standup.md
Fixes https://github.com/artsy/potential/issues/173
> Adds a note about notion in the standup doc

- .vscode/settings.json
- careers/README.md
- careers/engineering-managers.md
- careers/ladder.md
- careers/project-lead.md
- careers/summary.json
- careers/tech-lead.md
- culture/what-is-artsy.md
- 🎉 welcomes our 2018 engineering ladder to the open. 
- Stubs out some docs we want to be filling out
> Adds a careers section to README

- .vscode/settings.json
- README.md
- careers/README.md
- careers/engineering-managers.md
- careers/juniors.md
- careers/project-lead.md
- careers/summary.json
- careers/tech-lead.md
- culture/engineering-principles.md
- scripts/create-readmes.ts
A lot of the discussion around this doc happened in private, but now it's time for it to get some sunlight 👍 
This PR also updates some of our TOC around the docs, which happened before I got CI running.
> Adds a doc on how we find & evaluate juniors

- CONTRIBUTING.md
I made mostly cosmetic changes, but also wanted to raise the possibility of soliciting contributions from others. That part is separated in its own commit and we can discuss how we see external engineers contributing to our process. Thoughts?
> We welcome your contributions.

- events/happy-hour.md
Made some updates to clarify happy hour logistics as well as a suggestion of how to get invited.
> Happy hour is every last Thursday of the month.

- onboarding/managers.md
* Send 1st day schedule to private email account
* Simplify Slack channel setup
* Invite team members to welcome new hire and record for posterity
> [Manager Onboarding] Updates from new round of onboarding

- .github/ISSUE_TEMPLATE/engineering-onboarding.md
* Clarify ‘admin’ account
* Less Gravity specific focus
* Link more general reading resources
> [Engineer Onboarding] Updates from a new round of onboarding.

- playbooks/support/slack-notifications.md
> Provide directions on how to set up slack notifications on macOS

- playbooks/being-an-artsy-engineer.md
Wanted to get the ball rolling on this section as I've recently noticed some new apps without tests.
> @orta => Add a section about testing

- events/open-standup.md
This notes that we're doing it
> Adds front-end office hours to the announcements

- culture/slack.md
Fixes #22. This adds suggestions from Artsy staff, which are also linked do from the doc.
> Adds banter-y Slack channels

- recommendations/tech-learning.md
> Fix broken link

- practices/platform/hokusai.md
> k8s upgrade

- events/open-standup.md
> Adds a note at the end to put the docs in notion

- events/open-standup.md
Follow up on https://github.com/artsy/potential/issues/190
> Add hiring updates to open standup

- .github/ISSUE_TEMPLATE/engineering-onboarding.md
This is not so important, but I think it makes one feel more like they are a part of the team. Plus no one likes looking at those default Slack avatars! 😝
> Add poke on adding Slack avatar pic

- events/open-standup.md
This was made slightly more complicated by the staggered starts to on-call shifts, so I'm just clarifying things here.
> Clarify who runs standup

- playbooks/running-lunch-and-learn.md
Covers roughly my rubrics for figuring out what is wrong.
> Adds some technical trouble showing to running-lunch-and-learn.md

- resources/README.md
- resources/lnl.md
These are the ones I personally found useful. Looking for suggestions 🙌 
Wanted to add tech-stack videos but didn't know which one (if any) is the most relevant.
> Adds useful L&L videos

- .github/ISSUE_TEMPLATE/engineering-onboarding.md
Talked this over with @pepopowitz at writing office hours and we think it makes more sense to put this upfront, rather than as a pseudo-actionable item near the end.
> Moves docs-updating tip to top of list

- events/open-standup.md
> Adds practice updates to the standup

- onboarding/README.md
- playbooks/README.md
- playbooks/conferences.md
- resources/README.md
This adds a (public) playbook for attending and speaking at conferences.
> Add conferences playbook

- events/open-standup.md
- playbooks/support/README.md
> Add data practice to big standup; fix links

- playbooks/running-lunch-and-learn.md
This PR changes the docs from "hey let us know so we can handle it" to "hey let us know that you're working on this, and we're here to help."
> Updates expectations for running L&Ls

- .github/ISSUE_TEMPLATE/engineering-onboarding.md
Added _Lunch And Learn Highlights_ to onboarding resources.
> Add Lunch & Learn highlights to onboarding resources

- culture/README.md
- culture/peril.md
So that you don't have to consult the source code.
> Adds an overview on what peril does at Artsy

- README.md
🎉 
I'll look around and see if I can find other places where the front-end is noted, but this is a perfect start IMO.
> Set Ash & Justin as practice leads for the front-end practices

- events/open-standup.md
This one is your call, you could opt to have someone else from inside the team give updates (which is what we do with product ATM) but it's cool either way 👍
> Remove data from open standup

- practices/platform.md
Simple link for auth, is this appropriate @joey?
> added link to auth blog post to practice doc

- culture/slack.md
👋  Fixing while reading it, thanks for putting together these great documents 🙇
> Update store name and link to slack article

- playbooks/informationals.md
> Fix typo in La Colombe link

- culture/engineering-principles.md
> Fix typo in Engineering Principles

- culture/engineering-principles.md
New blog link: https://artsy.github.io/
> Update blog link

- events/README.md
- events/artsy-learns-to-code.md
This PR adds the initial _Artsy Learns to Code_ doc, and so this PR acts as the proposal. I'm hoping to solicit feedback from engineering mentors in the conversation below. 
**Please note** that we're planning to announce this to the rest of the company on Friday's Demo Day, so please have any feedback in by then.
> Artsy Learns to Code 

- playbooks/support/README.md
See https://github.com/artsy/README/issues/130 for context.
> Updates support README based on Jira Ops RFC

- events/happy-hour.md
> Updates for our new happy hour schedule

- onboarding/README.md
- onboarding/mentors.md
A start on a document about where to find success when mentoring a new hire.
> Mentorship at Artsy

- culture/highlights.md
🎉 🌮 ![selfie-0](https://i.imgur.com/YfVXAiE.png)
[_GitHub Selfies_](https://github.com/thieman/github-selfies/)
> Add MakeOffer

- culture/highlights.md
We should run a "Artsy Learns to Add Things to the Highlights Doc" next.
> Adds ALTC to highlights doc

- events/artsy-learns-to-code.md
> typo: you -> your in artsy-learns-to-code.md

- culture/slack.md
> Adding Productivity-Tips slack channel

- README.md
> Adds link to FE iOS Practice Overview

- events/artsy-learns-to-code.md
[As suggested](https://twitter.com/orta/status/1086007731318870017).
> Adds January ALTC status

- resources/README.md
- resources/leadership.md
Adding leadership resources pages.
> Adding leadership resources

- resources/leadership.md
Adding The Five Dysfunctions of a Team
> Adding The Five Dysfunctions of a Team

- practices/front-end.md
> Remove extraneous s in Visual Studio Code

- playbooks/retrospectives.md
Adding here links shared in other channels.
- 'Spotify Retro Kits' has a lot of interesting formats.
- 'How we made out team retros more effective' is an interested read about how important it is to be result oriented.
> Adding more resources to retrospective playbooks

- playbooks/deployments.md
The PR in Doppler is quite detailed about all the things I had to do with @ashkan18's help.
> Documented migration from Heroku to K8.

- .github/ISSUE_TEMPLATE/dependency-rfc.md
- .github/ISSUE_TEMPLATE/engineering-onboarding.md
- LICENSE.md
- culture/highlights.md
- culture/peril.md
- culture/slack.md
- dangerfile.ts
- package.json
- playbooks/graphql-schema-design.md
- playbooks/informationals.md
- playbooks/retrospectives.md
- playbooks/running-lunch-and-learn.md
- practices/history.md
- resources/artsy.md
- resources/blog.md
- resources/leadership.md
- resources/lnl.md
Mainly cleaning up some docs, adding the dependencies issue template, fixing some TODOs and updating some infra.
> Some spring cleaning in the repo

- .github/ISSUE_TEMPLATE/engineering-onboarding.md
I put it high up in the checklist, right after our first mention of setting up GitHub.
> Adds github-2fa to the on-boarding issue template

- playbooks/support/README.md
- playbooks/support/scheduling.md
There is already a note in the "Scheduling" playbook, but I added one to the general "Support" playbook.
> Update docs for trading shifts

- playbooks/support/README.md
- playbooks/support/responding.md
Some small additions that could help the next person.
> [Support] Small updates

- playbooks/support/README.md
- playbooks/technology-choices.md
I think we "decided" broadly that we want to implement pages in a responsive manner to provide a first-class experience to the growing and changing mobile audience. I thought I'd document that for posterity.
(Please ignore the prettier changes... I guess there were offending commits pushed earlier.)
> @damassi: Document that responsive page designs are [I think?] preferred

- playbooks/rfcs.md
- add missing comma
- remove unneeded `come`
> Fix typo in rfcs.md

- playbooks/support/README.md
Adds an explicit link to the training session!
> Adds link to onboarding session

- culture/engineering-principles.md
artsy/meta is deprecated and artsy/README is its spiritual successor
> Replace artsy/meta with artsy/README

- playbooks/support/responding.md
Here is my take on being more specific here.
> be more explicit of external communication for incidents

- playbooks/deployments.md
- playbooks/support/README.md
...with write access to the repo.
This has been confusing for a while. I did not do a complete dry run with these instructions, but have been through the process somewhat recently.
Note that when set up this way, I _don't_ think the `.circleci/config.yml` needs to include key fingerprints (unless there are multiple keys set up for the same hosts for some reason).
> @mbilokonsky: Document the exact steps for authorizing Circle

- events/lunch-and-learn.md
> Move lunch and learn to lunchtime 😉

- playbooks/running-lunch-and-learn.md
This should probably become a standard thing we do every time 😄
> Adds instructions to tweet thanks to external L&L speakers

- playbooks/hokusai.md
Update docs to include:
- Homebrew install
- Review apps
- Canary deployments
> update Hokusai docs

- events/open-standup.md
Given dB's departure, this PR updates the standup template.
> Removes CTO reference

- events/open-standup.md
Explicitly add prompt to each TL to source team's milestones during standup.
> [Stand-Up] Add prompt for each team's update

- culture/highlights.md
Dug up a few early highlights.
> Added 2009-2011 highlights

- events/open-standup.md
I missed a reference, this PR fixes it. Follow-up from #199
> Removes other CTO reference

- playbooks/hokusai.md
Install the AWS IAM authenticator binary and configure with the config file for devs
Depends on https://github.com/artsy/substance/pull/128
> docs for configuring hokusai / kubectl with the aws iam authenticator

- playbooks/deployments.md
When @eessex and I were pairing on updating Vibrations' hokusai config yesterday, we came across an issue with creating a r/w key for Circle. Updating these instructions to reflect the necessary change!
> Update keygen instructions

- playbooks/graphql-schema-design.md
> [GraphQL] Document identification specs.

- playbooks/kubernetes.md
Add some docs about configuring Kubernetes with admin credentials via IAM auth, and an example of identifying, draining and terminating a node with an unresponsive Docker daemon.
@eessex I based this off a [screenshot](https://artsy.slack.com/archives/CA8SANW3W/p1559675210026500?thread_ts=1559674010.024300&cid=CA8SANW3W) you took of a Pod in a bad state in the dashboard, but can't remember how to link images in this repo
> update Kubernetes docs about draining nodes when they fail to schedule pods

- playbooks/hokusai.md
#minor but I didn't see instructions for this anywhere!
> Add instructions on how to update environment variables

- playbooks/support/README.md
Updating this with the new links!
> Adds updated on-call onboarding video links

- culture/engineering-principles.md
- playbooks/README.md
- playbooks/open-sourcing.md
https://artsyproduct.atlassian.net/browse/GROW-1266
Follow up to https://artsy.slack.com/archives/C02BC3HEJ/p1558101262000400
This sets out a checklist of things to consider when taking an existing private repo and making it open-source.
> Document the process for taking a private repo and open-sourcing it

- playbooks/cloudflare.md
> add Cloudflare playbook

- playbooks/README.md
- playbooks/deployments.md
Lately many of our release PRs are just called the default `Staging`, so let's encourage more deliberate  choices.
(The other stuff is prettier.)
> @zephraph: Clarify that release PRs appreciate titles

- onboarding/engineering-introduction.md
- playbooks/engineer-workflow.md
- playbooks/support/README.md
- playbooks/system-criticality.md
- practices/platform.md
Follow up to https://github.com/artsy/potential/pull/279
> Update project list links to point to notion

- careers/ladder.md
We remapped the Engineering Ladder to Artsy's internal level.
This now reflects the accurate mapping.
> Update mapping between Engineering Ladder and Artsy Levels

- careers/ladder.md
These just show up as plaintext in the view.
> Remove style tags

- playbooks/support/scheduling.md
Just updating the docs after running through this with @dblandin.
> Updates to on-call schedule docs

- .github/ISSUE_TEMPLATE/dependency-rfc.md
Does this get my point across well?
> [Dep RFC] Add item about existing deps

- resources/mobile/README.md
- resources/mobile/learning-group/README.md
- resources/mobile/session-one.md
These are learning materials for the first session of the iOS Learning Group. The PR is a work-in-progress so that we can incorporate questions and feedback from _during_ the session into the canonical learning materials. I'll follow up with a final PR later today, ahead of our office hours.
> iOS Learning Group Session One Materials

- resources/mobile/README.md
- resources/mobile/learning-group/session-one.md
This adds a few fun/useful facts about the app, to help debug. It also adds a note about `xcode-select`.
> Adds some iOS fun facts

- resources/mobile/learning-group/README.md
- resources/mobile/learning-group/session-three.md
This week's materials are fairly short because a big chunk of them is following [some existing documentation](https://github.com/artsy/emission/blob/master/docs/adding_new_components.md). As usual, this PR is a WIP until we fill it out with feedback we'll get during the session.
> iOS Learning Group Session Three Material

- resources/mobile/xcode.md
Also includes instructions on how to install new simulators in old Xcode versions.
> Updates instructions to install multiple versions

- events/open-standup.md
We haven't had updates for a while so it was suggested that we remove this part of the agenda.
> Yank PM update

- resources/mobile/learning-group/session-two.md
Looks like maybe autocorrect struck here, so I just changed `tax` back to `tsx`
> Fix syntax highlighting for tsx snippet

- resources/mobile/learning-group/README.md
- resources/mobile/learning-group/session-three.md
- resources/mobile/learning-group/session-two.md
> Minor iOS learning doc updates

- resources/mobile/learning-group/README.md
- resources/mobile/learning-group/session-five.md
Notes from this morning's mob session.
> iOS Learning Group Session Five materials

- playbooks/graphql-schema-design.md
* Updates `snake_case` examples to `camelCase`.
* Implicitly addresses not to have fields that take IDs of specific nodes, but that we should have a `nodes` field for that at some point.
* Addresses field resolvers being smart about what upstream API to use depending on arguments, as long as they aren’t mutually exclusive to the extend that it makes the design unintuitive. E.g. these arguments both existing in the same field make no sense `artworks(specificIDs: [ID], size: Int)`
> [GraphQL] Update based on recent work.

- playbooks/support/responding.md
Thank you to @dblandin for doing a 👌 job at updating the timeline on a recent incident! (got to use that as an example. 😄 )
> Improves on-call responding instructions for updating the timeline

- onboarding/new-hires.md
The important change is the link updates-- the rest is auto-formatting.
> Fix onboarding links that need to point to potential

- events/open-standup.md
I've added a [template](https://www.notion.so/artsy/Month-Day-Year-fbc9df949fef430a9f9359f34158dec6) in notion for easily creating new standup notes. This'll just make it a _little_ simpler to run standup.
> Add comment about updating notion template

- playbooks/technology-choices.md
- playbooks/technology_radar/data.csv
Our recent engineering skills survey revealed a pattern of problems with how Artsy makes technology choices, including low and/or decreasing scores on questions like:
* _I understand how Artsy Engineering makes choices about technology_
* _Artsy makes Quality Worthy of Art technology choices_
* _I understand how to select an appropriate technology stack for a new project_
* _I understand when it is appropriate to create a new service vs. adding to an existing one_
I revisited our relevant playbook searching for ways to remedy this and it had a number of obvious problems. Some of the "choices" it documents are out-of-date, and it nods to 2 completely different vocabularies for the stages of evaluating technology.
This PR tries to consolidate on the tech "radar" framework and adopt its …
> Consolidate playbook for responsible tech choices

- practices/platform.md
> Fixing platform learning link

- playbooks/README.md
- playbooks/technology-choices.md
@dleve123 and I have been working for some time on defining a process for making technology decisions at Artsy. While the solution we landed on seems straightforward, I want to describe our process so that it's clear how we ended up here.
First, the rationale. Not all engineers at Artsy are familiar with how we make decisions (we saw this in recent Culture Amp surveys). There is a desire to know how we make decisions, and having a documented process is really important to make sure we build+maintain a culture where every engineer feels like they have a voice.
Daniel and I worked through a few different models, but none of them really suited our team. They were good frameworks, but introduced more and more process. This ran contrary to our Engineering Guiding Principle of [Minimum Viable …
> Frame technical plans as a way to make decisions

- playbooks/technology_radar/artsy-tech-radar.csv
Clarify that modifications to v1 are discouraged.
Is this language right? Is the "techniques" category right?
> Hold on MP's v1 schema and adopt v2

- playbooks/migrating-sidekiq.md
Plz comment and suggest edits!  Want this to be as clear as possible!
> #WIP add migrating sidekiq playbook

- events/README.md
- events/artsy-learns-to-code-v2.md
First draft for the format of ALTC v2, based off of what we discussed in earlier brainstorm sessions. Eager to get feedback before making this an official RFC!
> [RFC] First draft for ALTC v2

- events/artsy-learns-to-code-v2.md
To update the README with more resources in the future!
> Add barry's resource for shell, vim, git, etc basics as a resource for ALTC v2

- careers/README.md
- careers/tech-lead.md
Remove old WIP and link to internal doc instead.
> Tech Lead Doc

- playbooks/migrating-redis.md
- playbooks/migrating-sidekiq.md
Follow-up to https://github.com/artsy/docker-images/pull/62/
> Updates to migrate-redis and migrate-sidekiq playbooks

- events/README.md
- events/writing-office-hours.md
@jpotts244 thanks for the push on this, and sorry it took so long to get to! Let me know what I can clarify here.
> Adds docs for Writing Office Hours

- events/README.md
- events/peer-labs.md
I only named myself explicitly, but I'm open to adding other engineers. Didn't want to step on toes, so just add yourself using a GitHub suggestion. 
Fixes #11.
> Adds docs for peer labs

- playbooks/support/responding.md
Follow up to https://artsyproduct.atlassian.net/browse/PLATFORM-2134, add instructions for using OpsGenie notifications/alerts.
> Add instructions for OpsGenie alerts

- playbooks/technology_radar/artsy-tech-radar.csv
It was briefly [discussed](https://artsy.slack.com/archives/CP9P4KR35/p1588197242487700?thread_ts=1588196125.480000&cid=CP9P4KR35) that heroku should be added to a `hold` state.
> Add Heroku as a hold

- resources/mobile/README.md
This simply updates the wording that says the learning group is in progress.
> Updated to reflect that the learning group is over

- events/lunch-and-learn.md
> Adds Bed Stuy Strong presentation

- culture/what-is-artsy.md
Insert the new values, copied from the [slide deck](https://docs.google.com/presentation/d/1Hk8wX9SRmKlf9mQsYFsGVF7jbHOFikaeFRVo7PEG0DE/edit#slide=id.g7f6d69116f_6_74). There might be more stuff here that's out of date, but this is what jumped out at me on a first reading.
@iskounen I assigned this to you, since it looks like you've been active on other open PRs. I guess that this repo could do with some ❤️ generally, but I can see how it tends to drop below the radar! I'm happy to do some more updating as I discover things, if that would make sense, but I don't really feel like I'm qualified to make the kind of judgement calls that would be needed to bring some of it up to date.
> fix: update values

- .github/ISSUE_TEMPLATE/dependency-rfc.md
In some recent new dependency RFC discussions, we had to spend time clarifying the motivation behind adding the dependency. I'd like to update the RFC template with more instructions on exactly what goes in the "Motivation" section, including requests for sample code or designs.
Let me know what you think, I'm open to feedback!
> Clarifies motivation section of new dependency RFCs

- playbooks/support/README.md
> update link to gdrive

- events/open-standup.md
- package-lock.json
- Adding explicit call out to async communication
- Adding new section for optional Q&A / open discussion
> Updating stand up agenda

- playbooks/support/README.md
i missed it, so maybe others might too 😬.
> fix: clarify on-call procedure

- onboarding/engineering-introduction.md
> chore: update standup time

- culture/what-is-artsy.md
we also need to update the _How do we make money_ section
> fix: update values again

- onboarding/sessions/tour-of-collector-ux.md
https://artsyproduct.atlassian.net/browse/GALL-2201
Clean up references to lewitt-api.
> Remove reference to lewitt-api (GALL-2201)

- playbooks/management/reading-list.md
This PR adds a new doc to our fledgling `management` section that includes a list of helpful/recommended resources.
I started off the list with a few book and newsletter recommendations, but I'm sure we all have more of our favorites that we can add!
> feat: Adds a reading list doc with a few entries

- playbooks/support/scheduling.md
Paired with Devon
Adds steps on how to signup for one of the holiday volunteer on-call slots
> Update on-call documentation include steps for Holiday Scheduling

- events/open-standup.md
It came up in standup on Monday that the practices have new names – let's update the docs 🙌 I also added back in the Front-End / Web practice.
> chore: update practice names

- README.md
Adds details for mobile, web and data practices.
> feat: all the new practice details

- playbooks/kubernetes.md
> chore: k8s update cleanup.

- culture/slack.md
- practices/README.md
- practices/mobile.md
- practices/web.md
- resources/mobile/README.md
- resources/mobile/learning-group/session-four.md
- resources/tech-learning.md
This PR  updates documentation to reflect the new practices namings.
Context: **RFC** https://github.com/artsy/README/issues/349
> Update documentation to reflect the new practices namings

- playbooks/deployments.md
> small docs update while running through that list

- events/open-standup.md
@emmadickson @alexpopa-artsy would one of you volunteer to share updates from the data practice at standup?
> Adding data practice to standup updates

- playbooks/README.md
- playbooks/vendor-evaluations.md
Spinning off of a build vs buy discussion (https://www.notion.so/artsy/Build-vs-Buy-2bcc2435bf7549ca97a947ec9ac1d2c8), here's a draft framework/checklist of things to consider when evaluating a vendor. I figure this would work best as an RFC, but please let me know if this would live better in another format.
Thanks to @SamRozen for the suggestion and @sweir27 for the push to draft this up!
> RFC: draft vendor evaluation playbook

- practices/README.md
Tiny start to a "playbook" for practices.
As discussed, some other things this could document include:
* example agenda and list of candidate topics
* steps to create a practice Jira "board" via labels and saved filters
> Suggest rule of thumb for what to do in practices vs. product teams

- careers/ladder.md
Updating Technical Leads section in our career ladder to more accurately reflect the current responsibilities.
> fix: Update Technical Leads

- culture/slack.md
- playbooks/engineer-workflow.md
More fixes in preparation for future onboarding.
> Refresh list of engineering-related slack channels

- playbooks/kubernetes.md
- playbooks/rename-master-to-main.md
Writing a guide on what repos to start renaming the main branch to "main". Please feel free to add to the lists or comment if some repo is not a good candidate to start with because there might be a hidden complexity in it.
> docs: guide on how to start renaming main branches in repos

- practices/history.md
- practices/mobile.md
- practices/platform.md
Some of these tweaks are based solely on my opinions, but I felt like I should suggest these while reading these documents!
> docs: Minor grammar and clarity improvements

- playbooks/development-environments.md
Removed a sentence that caused some confusion and seems unnecessary. Less is more in this case.
> chore: update developer-environments doc

- playbooks/taming-notifications.md
Adds a playbook on how to set up notifications so that they don't disturb you outside of working hours.
> feat: notifications playbook

- resources/tech-learning.md
> Docs: Update tech-learning.md

- conference-notes/README.md
- onboarding/README.md
- onboarding/engineering-introduction.md
- playbooks/cloudflare.md
- playbooks/development-environments.md
- playbooks/graphql-schema-design.md
- playbooks/incident-handling.md
- playbooks/kubernetes.md
- playbooks/migrating-postgres-with-rubyrep.md
- playbooks/migrating-redis.md
- playbooks/migrating-sidekiq.md
- resources/artsy.md
- resources/mobile/README.md
- resources/mobile/finding-code.md
- resources/mobile/learning-group/session-one.md
- resources/mobile/learning-group/session-two.md
- resources/tech-learning.md
This is an attempt to fix some broken links.
This was done using a broken URL scanner. What I couldn't resolve automatically I added a `TODO` to be later discussed with the team, so please jump in if you know where the new link is or if we can edit/remove it because it's now deprecated.
> chore: broken links cleanup

- playbooks/rename-master-to-main.md
Just a small improve on the playbook for branch renaming.
> Add Airflow as a possible disruption when renaming branchs

- culture/slack.md
My first PR! 🎉
A bit of update for the slack channels list.
> fix: remove archived channels and rename one

- playbooks/engineer-workflow.md
Also, change `master` to `main`.
> docs: add PR best practices to engineer workflow

- playbooks/deployments.md
We never formally updated this after last quarter's successful push to get almost all projects deploying continuously.
This PR documents the current preference for continuous deployment and provides some rationale.
> Document our recommendation for continuous deployment

- culture/peril.md
Update documentation of how the team currently uses Peril.
> docs: update peril documentation

- README.md
> docs: rfc links in docs

- onboarding/sprint-rotation.md
**Changes Summary in sprint-rotation.md**
- Adding Rotation buddy responsibilities 
- Removing forced line wraps.
- Adding a suggestion to organize 1:1 with different team members
- Reducing the heading by 1, since the document only contained Header 2+.
> Rotation Docs Updates

- RFCs/README.md
- RFCs/use-prs-instead-of-issues.md
- playbooks/rfcs.md
Proposing a new approach for RFCs.
> rfc: use PRs instead of issues for RFCs

- README.md
- events/README.md
- playbooks/README.md
- playbooks/practices.md
- resources/README.md
This PR does the following:
- Update the practice leads for each of our practices
- Extend facilitating a practice docs
_Prettier and the generate read-me script are acting a bit weird here 😄 sorry about it_
> chore: refresh practice docs

- playbooks/incident-handling.md
Add cloudflare to list of dashboards to monitor
> Chore: Add cloudflare to list of dashboards to monitor

- hiring/interviewing.md
Updating Interviewing @ Artsy page
> feat: update Interviewing at Artsy page

- RFCs/README.md
> docs: Update README.md

- playbooks/engineer-workflow.md
> fix: update link

- playbooks/README.md
> docs: add cultural and technical playbook sections

- playbooks/deployments.md
As a new user I found it wasn't clear which settings this was referring to specifically so specified where these settings were.
> chore: update deployments.md

- README.md
While reviewing all the stale info in this repo I decided to start with updating this list.
/cc @cavvia @tam-kis @TMcMeans @MrSltun @gkartalis @mc-jones
> Update practice leads

- playbooks/incident-handling.md
Addressing action item from inc-180
https://artsy.app.opsgenie.com/reports/post-mortem/bc69f1ee-85d1-4a0d-b956-a1079e8645cb/detail
> Add a note about OpsGenie notifications to the "Track the incident" section

- playbooks/technology_radar/artsy-tech-radar.csv
add codepush as a tool we are trialing :)
> docs(tech-radar): add codepush to trialed tools

- RFCs/switch-to-standardrb.md
- playbooks/technology_radar/artsy-tech-radar.csv
Adds an RFC for switching to standardrb - see the markdown file that this PR adds for the details!
> Add RFC for standardrb

- culture/highlights.md
> Mark partner offers on saves in history

- RFCs/platform-practice-4ps.md
This is the RFC for the platform practice, after discussions in the platform practice and with @erikdstock @mc-jones and @joeyAghion
> Add RFC: platform-practice-4ps.md

- playbooks/incident-handling.md
Link to the [draft] playbook for handling potential security incidents.
> chore: link to security incident-handling doc

- README.md
- RFCs/README.md
- playbooks/README.md
- playbooks/technical-planning.md
- playbooks/technology_radar/artsy-tech-radar.csv
Adds to the Tech Radar [some conclusions](https://docs.google.com/spreadsheets/d/1xWJks1wbe8qV44cr636MUaU0rZyAkNYNob3IHigCZY4/edit?usp=sharing) reached by the AI Innovation Squad.
(Radar change is in db2993bcce91047ba01dc6bae95022f87be45260)
> feat(radar): add recent AI squad findings

- culture/slack.md
Adding #sup-chats to slack.md to ensure new starters know about it.
> docs: Adding #sup-chats to slack.md

- playbooks/development-environments.md
- playbooks/version-managers.md
Updates things to point from asdf -> mise. 
See:
- RFC: https://github.com/artsy/README/issues/550
> chore: Migrate from asdf to mise

- README.md
This PR updates the web practice lead in README.md
> chore: update web practice lead link in README.md
